<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Daftar_penilai extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Daftar_penilai_model');
        if (!$this->session->userdata('isLogin')) {
            redirect('auth/index');
        }
    } 

    /*
     * Listing of daftar_penilai
     */
    function index()
    {
        $data['daftar_penilai'] = $this->Daftar_penilai_model->get_all_daftar_penilai();
        
        $data['_view'] = 'daftar_penilai/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new daftar_penilai
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_mhs' => $this->input->post('id_mhs'),
				'id_periode' => $this->input->post('id_periode'),
            );
            
            $daftar_penilai_id = $this->Daftar_penilai_model->add_daftar_penilai($params);
            redirect('daftar_penilai/index');
        }
        else
        {            
            $data['_view'] = 'daftar_penilai/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a daftar_penilai
     */
    function edit($id_penilai)
    {   
        // check if the daftar_penilai exists before trying to edit it
        $data['daftar_penilai'] = $this->Daftar_penilai_model->get_daftar_penilai($id_penilai);
        
        if(isset($data['daftar_penilai']['id_penilai']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_mhs' => $this->input->post('id_mhs'),
					'id_periode' => $this->input->post('id_periode'),
                );

                $this->Daftar_penilai_model->update_daftar_penilai($id_penilai,$params);            
                redirect('daftar_penilai/index');
            }
            else
            {
                $data['_view'] = 'daftar_penilai/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The daftar_penilai you are trying to edit does not exist.');
    } 

    /*
     * Deleting daftar_penilai
     */
    function remove($id_penilai)
    {
        $daftar_penilai = $this->Daftar_penilai_model->get_daftar_penilai($id_penilai);

        // check if the daftar_penilai exists before trying to delete it
        if(isset($daftar_penilai['id_penilai']))
        {
            $this->Daftar_penilai_model->delete_daftar_penilai($id_penilai);
            redirect('daftar_penilai/index');
        }
        else
            show_error('The daftar_penilai you are trying to delete does not exist.');
    }
    
}
