<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Dashboard extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        if (!$this->session->userdata('isLogin')) {
            redirect('auth/index');
        }
    }

    public function index()
    {
        $data['title'] = ['title' => 'Home'];
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main', $data);
    }
}
