<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Kuisioner extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('Kuisioner_model');
    }

    /*
     * Listing of kuisioner
     */
    public function index()
    {
        $data['title'] = ['title' => 'Pertanyaan'];
        $data['_view'] = 'kuisioner/index';
        $this->load->view('layouts/main', $data);
    }

    public function getdata()
    {
        $result = $this->Kuisioner_model->get_all_kuisioner();
        echo json_encode($result);
    }

    /*
     * Adding a new kuisioner
     */
    public function add()
    {
        $params = json_decode($this->security->xss_clean($this->input->raw_input_stream), true);
        $result = $this->Kuisioner_model->add_kuisioner($params);
        echo json_encode($result);
    }

    /*
     * Editing a kuisioner
     */
    public function edit()
    {
        // check if the kuisioner exists before trying to edit it
        $params = json_decode($this->security->xss_clean($this->input->raw_input_stream), true);
        $result = $this->Kuisioner_model->update_kuisioner($params);
        echo json_encode($result);
    }

    /*
     * Deleting kuisioner
     */
    public function remove($id_kuisioner)
    {
        $kuisioner = $this->Kuisioner_model->get_kuisioner($id_kuisioner);

        // check if the kuisioner exists before trying to delete it
        if (isset($kuisioner['id_kuisioner'])) {
            $this->Kuisioner_model->delete_kuisioner($id_kuisioner);
            echo json_decode(['message' => true]);
        } else {
            http_response_code(400);
            echo json_decode(['message' => false]);
        }
    }
}
