<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Layanan extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('Layanan_model');
    }

    /*
     * Listing of layanan
     */
    public function index()
    {

        $data['title'] = ['title' => 'Layanan'];
        $data['_view'] = 'layanan/index';
        $this->load->view('layouts/main', $data);
    }

    public function getdata()
    {
        $data = $this->Layanan_model->get_all_layanan();
        echo json_encode($data);
    }

    /*
     * Adding a new layanan
     */
    public function add()
    {
        $params = json_decode($this->security->xss_clean($this->input->raw_input_stream), true);
        $result = $this->Layanan_model->add_layanan($params);
        echo json_encode($result);
    }

    /*
     * Editing a layanan
     */
    public function edit()
    {
        $params = json_decode($this->security->xss_clean($this->input->raw_input_stream), true);
        $result = $this->Layanan_model->update_layanan($id_layanan, $params);
        echo json_encode($result);
    }

    /*
     * Deleting layanan
     */
    public function remove($id_layanan)
    {
        $layanan = $this->Layanan_model->get_layanan($id_layanan);

        // check if the layanan exists before trying to delete it
        if (isset($layanan['id_layanan'])) {
            $this->Layanan_model->delete_layanan($id_layanan);
            echo json_decode(['message' => true]);
        } else {
            http_response_code(400);
            echo json_decode(['message' => false]);
        }

    }

}
