<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Nilai_kepuasan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Nilai_kepuasan_model');
        if (!$this->session->userdata('isLogin')) {
            redirect('auth/index');
        }
    } 

    /*
     * Listing of nilai_kepuasan
     */
    function index()
    {
        $data['nilai_kepuasan'] = $this->Nilai_kepuasan_model->get_all_nilai_kepuasan();
        
        $data['_view'] = 'nilai_kepuasan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new nilai_kepuasan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_periode' => $this->input->post('id_periode'),
				'id_kuisioner' => $this->input->post('id_kuisioner'),
				'id_range' => $this->input->post('id_range'),
            );
            
            $nilai_kepuasan_id = $this->Nilai_kepuasan_model->add_nilai_kepuasan($params);
            redirect('nilai_kepuasan/index');
        }
        else
        {            
            $data['_view'] = 'nilai_kepuasan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a nilai_kepuasan
     */
    function edit($id_nilai)
    {   
        // check if the nilai_kepuasan exists before trying to edit it
        $data['nilai_kepuasan'] = $this->Nilai_kepuasan_model->get_nilai_kepuasan($id_nilai);
        
        if(isset($data['nilai_kepuasan']['id_nilai']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_periode' => $this->input->post('id_periode'),
					'id_kuisioner' => $this->input->post('id_kuisioner'),
					'id_range' => $this->input->post('id_range'),
                );

                $this->Nilai_kepuasan_model->update_nilai_kepuasan($id_nilai,$params);            
                redirect('nilai_kepuasan/index');
            }
            else
            {
                $data['_view'] = 'nilai_kepuasan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The nilai_kepuasan you are trying to edit does not exist.');
    } 

    /*
     * Deleting nilai_kepuasan
     */
    function remove($id_nilai)
    {
        $nilai_kepuasan = $this->Nilai_kepuasan_model->get_nilai_kepuasan($id_nilai);

        // check if the nilai_kepuasan exists before trying to delete it
        if(isset($nilai_kepuasan['id_nilai']))
        {
            $this->Nilai_kepuasan_model->delete_nilai_kepuasan($id_nilai);
            redirect('nilai_kepuasan/index');
        }
        else
            show_error('The nilai_kepuasan you are trying to delete does not exist.');
    }
    
}
