<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Periode extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Periode_model');
    } 

    /*
     * Listing of periode
     */
    function index()
    {
        $data['periode'] = $this->Periode_model->get_all_periode();
        
        $data['_view'] = 'periode/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new periode
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_thakademik' => $this->input->post('id_thakademik'),
				'id_prog_studi' => $this->input->post('id_prog_studi'),
				'jml_mhs_aktif' => $this->input->post('jml_mhs_aktif'),
				'jml_responden' => $this->input->post('jml_responden'),
				'persentase_responden' => $this->input->post('persentase_responden'),
            );
            
            $periode_id = $this->Periode_model->add_periode($params);
            redirect('periode/index');
        }
        else
        {            
            $data['_view'] = 'periode/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a periode
     */
    function edit($id_periode)
    {   
        // check if the periode exists before trying to edit it
        $data['periode'] = $this->Periode_model->get_periode($id_periode);
        
        if(isset($data['periode']['id_periode']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_thakademik' => $this->input->post('id_thakademik'),
					'id_prog_studi' => $this->input->post('id_prog_studi'),
					'jml_mhs_aktif' => $this->input->post('jml_mhs_aktif'),
					'jml_responden' => $this->input->post('jml_responden'),
					'persentase_responden' => $this->input->post('persentase_responden'),
                );

                $this->Periode_model->update_periode($id_periode,$params);            
                redirect('periode/index');
            }
            else
            {
                $data['_view'] = 'periode/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The periode you are trying to edit does not exist.');
    } 

    /*
     * Deleting periode
     */
    function remove($id_periode)
    {
        $periode = $this->Periode_model->get_periode($id_periode);

        // check if the periode exists before trying to delete it
        if(isset($periode['id_periode']))
        {
            $this->Periode_model->delete_periode($id_periode);
            redirect('periode/index');
        }
        else
            show_error('The periode you are trying to delete does not exist.');
    }
    
}
