<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Periode extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('Periode_model');
        if (!$this->session->userdata('isLogin')) {
            redirect('auth/index');
        }
    }

    /*
     * Listing of periode
     */
    public function index()
    {
        $data['title'] = ['title' => 'Periode'];

        $data['_view'] = 'periode/index';
        $this->load->view('layouts/main', $data);
    }

    public function getdata()
    {
        $this->load->library('mylib');
        $result['periode'] = $this->Periode_model->get_all_periode();
        $result['tahunakademikaktive'] = $this->mylib->restapi('tahunakademik/getTaAktif', $this->session->userdata('Token'))->data[0];
        $result['tahunakademik'] = $this->mylib->restapi('tahunakademik', $this->session->userdata('Token'));
        echo json_encode($result);
    }

    /*
     * Adding a new periode
     */
    public function add()
    {
        $data = json_decode($this->security->xss_clean($this->input->raw_input_stream), true);
        $result = $this->Periode_model->add_periode($data);
        echo json_encode($result);
    }

    /*
     * Editing a periode
     */
    public function edit()
    {
        // check if the periode exists before trying to edit it
        $params = json_decode($this->security->xss_clean($this->input->raw_input_stream), true);
        $result = $this->Periode_model->update_periode($params);
        echo json_encode($result);

    }

    /*
     * Deleting periode
     */
    public function remove($id_periode)
    {
        $periode = $this->Periode_model->get_periode($id_periode);

        // check if the periode exists before trying to delete it
        if (isset($periode['id_periode'])) {
            $this->Periode_model->delete_periode($id_periode);
            redirect('periode/index');
        } else {
            show_error('The periode you are trying to delete does not exist.');
        }

    }

}
