<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Range_nilai extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Range_nilai_model');
    } 

    /*
     * Listing of range_nilai
     */
    function index()
    {
        $data['title'] = ['title'=>'Range Nilai'];
        
        $data['_view'] = 'range_nilai/index';
        $this->load->view('layouts/main',$data);
    }

    function getdata()
    {
        $data = $this->Range_nilai_model->get_all_range_nilai();
        echo json_encode($data);
    }

    /*
     * Adding a new range_nilai
     */
    function add()
    {   
        $data = json_decode($this->security->xss_clean($this->input->raw_input_stream), true);
        $result = $this->Range_nilai_model->add_range_nilai($data);
        echo json_encode($result);
    }  

    /*
     * Editing a range_nilai
     */
    function edit()
    {   
        $data = json_decode($this->security->xss_clean($this->input->raw_input_stream), true);
        // check if the range_nilai exists before trying to edit it
        $result = $this->Range_nilai_model->update_range_nilai($data);  
        echo json_encode($result);
    } 

    /*
     * Deleting range_nilai
     */
    function remove($id_range)
    {
        $range_nilai = $this->Range_nilai_model->get_range_nilai($id_range);

        // check if the range_nilai exists before trying to delete it
        if(isset($range_nilai['id_range']))
        {
            $this->Range_nilai_model->delete_range_nilai($id_range);
            echo json_encode(['message'=>true]);
        }
        else{
            http_response_code(404);
            echo json_encode(['message'=>false]);
        }
        
            
    }
    
}
