<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Aspek_penilaian_model extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
    }

    /*
     * Get aspek_penilaian by id_aspek
     */
    public function get_aspek_penilaian($id_aspek)
    {
        return $this->db->get_where('aspek_penilaian', array('id_aspek' => $id_aspek))->row_array();
    }

    /*
     * Get all aspek_penilaian
     */
    public function get_all_aspek_penilaian()
    {
        $this->db->order_by('id_aspek', 'ASC');
        return $this->db->get('aspek_penilaian')->result();
    }

    /*
     * function to add new aspek_penilaian
     */
    public function add_aspek_penilaian($params)
    {
        $this->db->insert('aspek_penilaian', $params);
        $params['id_aspek'] = $this->db->insert_id();
        return $params;
    }

    /*
     * function to update aspek_penilaian
     */
    public function update_aspek_penilaian($params)
    {
        $item = [
            'nm_aspek' => $params['nm_aspek'],
            'deskripsi' => $params['deskripsi'],
        ];
        $this->db->where('id_aspek', $params['id_aspek']);
        $this->db->update('aspek_penilaian', $item);
        return $params;
    }

    /*
     * function to delete aspek_penilaian
     */
    public function delete_aspek_penilaian($id_aspek)
    {
        return $this->db->delete('aspek_penilaian', array('id_aspek' => $id_aspek));
    }
}
