<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Hasil_penilaian_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get hasil_penilaian by npm
     */
    function get_hasil_penilaian($npm)
    {
        return $this->db->get_where('hasil_penilaian',array('npm'=>$npm))->row_array();
    }
        
    /*
     * Get all hasil_penilaian
     */
    function get_all_hasil_penilaian()
    {
        $this->db->order_by('npm', 'desc');
        return $this->db->get('hasil_penilaian')->result_array();
    }
        
    /*
     * function to add new hasil_penilaian
     */
    function add_hasil_penilaian($params)
    {
        $this->db->insert('hasil_penilaian',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update hasil_penilaian
     */
    function update_hasil_penilaian($npm,$params)
    {
        $this->db->where('npm',$npm);
        return $this->db->update('hasil_penilaian',$params);
    }
    
    /*
     * function to delete hasil_penilaian
     */
    function delete_hasil_penilaian($npm)
    {
        return $this->db->delete('hasil_penilaian',array('npm'=>$npm));
    }
}
