<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Kuisioner_model extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('Aspek_penilaian_model');
        $this->load->model('Layanan_model');

    }

    /*
     * Get kuisioner by id_kuisioner
     */
    public function get_kuisioner($id_kuisioner)
    {
        return $this->db->get_where('kuisioner', array('id_kuisioner' => $id_kuisioner))->row_array();
    }

    /*
     * Get all kuisioner
     */
    public function get_all_kuisioner()
    {
        $data = [
            'aspek' => $this->Aspek_penilaian_model->get_all_aspek_penilaian(),
            'questioner' => $this->db->query("SELECT
                    `kuisioner`.`id_kuisioner`,
                    `kuisioner`.`pertanyaan`,
                    `aspek_penilaian`.`id_aspek`,
                    `aspek_penilaian`.`nm_aspek`,
                    `aspek_penilaian`.`deskripsi`
                FROM
                    `kuisioner`
                    LEFT JOIN `aspek_penilaian` ON `aspek_penilaian`.`id_aspek` =
                `kuisioner`.`id_aspek`
                ORDER BY `aspek_penilaian`.`id_aspek`, `kuisioner`.`id_kuisioner` ASC")->result_array(),
            'layanan' => $this->Layanan_model->get_all_layanan(),
        ];
        return $data;
    }

    /*
     * function to add new kuisioner
     */
    public function add_kuisioner($params)
    {
        $item = [
            'pertanyaan' => $params['pertanyaan'],
            'id_aspek' => $params['id_aspek'],
        ];
        $this->db->insert('kuisioner', $item);
        $params['id_kuisioner'] = $this->db->insert_id();
        return $params;
    }

    /*
     * function to update kuisioner
     */
    public function update_kuisioner($params)
    {
        $this->db->where('id_kuisioner', $params['id_kuisioner']);
        $result = $this->db->update('kuisioner', ["pertanyaan" => $params['pertanyaan']]);
        return $result;
    }

    /*
     * function to delete kuisioner
     */
    public function delete_kuisioner($id_kuisioner)
    {
        return $this->db->delete('kuisioner', array('id_kuisioner' => $id_kuisioner));
    }
}
