<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Nilai_kepuasan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get nilai_kepuasan by id_nilai
     */
    function get_nilai_kepuasan($id_nilai)
    {
        return $this->db->get_where('nilai_kepuasan',array('id_nilai'=>$id_nilai))->row_array();
    }
        
    /*
     * Get all nilai_kepuasan
     */
    function get_all_nilai_kepuasan()
    {
        $this->db->order_by('id_nilai', 'desc');
        return $this->db->get('nilai_kepuasan')->result_array();
    }
        
    /*
     * function to add new nilai_kepuasan
     */
    function add_nilai_kepuasan($params)
    {
        $this->db->insert('nilai_kepuasan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update nilai_kepuasan
     */
    function update_nilai_kepuasan($id_nilai,$params)
    {
        $this->db->where('id_nilai',$id_nilai);
        return $this->db->update('nilai_kepuasan',$params);
    }
    
    /*
     * function to delete nilai_kepuasan
     */
    function delete_nilai_kepuasan($id_nilai)
    {
        return $this->db->delete('nilai_kepuasan',array('id_nilai'=>$id_nilai));
    }
}
