<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Periode_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get periode by id_periode
     */
    function get_periode($id_periode)
    {
        return $this->db->get_where('periode',array('id_periode'=>$id_periode))->row_array();
    }
        
    /*
     * Get all periode
     */
    function get_all_periode()
    {
        $this->db->order_by('id_periode', 'desc');
        return $this->db->get('periode')->result_array();
    }
        
    /*
     * function to add new periode
     */
    function add_periode($params)
    {
        $this->db->insert('periode',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update periode
     */
    function update_periode($id_periode,$params)
    {
        $this->db->where('id_periode',$id_periode);
        return $this->db->update('periode',$params);
    }
    
    /*
     * function to delete periode
     */
    function delete_periode($id_periode)
    {
        return $this->db->delete('periode',array('id_periode'=>$id_periode));
    }
}
