<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Periode_model extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
    }

    /*
     * Get periode by id_periode
     */
    public function get_periode($id_periode)
    {
        return $this->db->get_where('periode', array('id_periode' => $id_periode))->row_array();
    }

    /*
     * Get all periode
     */
    public function get_all_periode()
    {
        $this->db->order_by('id_periode', 'desc');
        return $this->db->get('periode')->result_array();
    }

    /*
     * function to add new periode
     */
    public function add_periode($params)
    {
        $this->db->insert('periode', $params);
        $params['id_periode'] = $this->db->insert_id();
        return $params;
    }

    /*
     * function to update periode
     */
    public function update_periode($params)
    {
        $item = [
            'selesai' => $params['selesai'],
        ];
        $this->db->where('id_periode', $params['id_periode']);
        $this->db->update('periode', $item);
        return $params;
    }

    /*
     * function to delete periode
     */
    public function delete_periode($id_periode)
    {
        return $this->db->delete('periode', array('id_periode' => $id_periode));
    }
}
