<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Range_nilai_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get range_nilai by id_range
     */
    function get_range_nilai($id_range)
    {
        return $this->db->get_where('range_nilai',array('id_range'=>$id_range))->row_array();
    }
        
    /*
     * Get all range_nilai
     */
    function get_all_range_nilai()
    {
        $this->db->order_by('id_range', 'desc');
        return $this->db->get('range_nilai')->result_array();
    }
        
    /*
     * function to add new range_nilai
     */
    function add_range_nilai($params)
    {
        $this->db->insert('range_nilai',$params);
        $params['id_range']=$this->db->insert_id();
        return $params;
    }
    
    /*
     * function to update range_nilai
     */
    function update_range_nilai($params)
    {
        $item = [
            'nilai'=> $params['nilai'],
            'deskripsi'=> $params['deskripsi']
        ];
        $this->db->where('id_range',$params['id_range']);
        $this->db->update('range_nilai',$item);
        return $params;
    }
    
    /*
     * function to delete range_nilai
     */
    function delete_range_nilai($id_range)
    {
        return $this->db->delete('range_nilai',array('id_range'=>$id_range));
    }
}
